### ISSUE TITLE
notes from call 

### ISSUE THREAD

**Issue by piamancini** [sustainers/events#1]
open event 
travel budget (Ben)
feedback: 
more notes
using raw material
tech repo
design (justin)
Chris (live sketching / unconference)
follow up on projects that get created during sustain
how do we make up the list? (ben)
Goals 
Pictures 
make these notes into issues (Pia)

**Comment by daiyi** [comment]
![handwritten notes](https://user-images.githubusercontent.com/1589186/39368407-58428a54-49ee-11e8-8133-f98c6fc574fa.JPG)

**Comment by daiyi** [comment]
I noticed there's also a project board on this repo! will we be using that to track organisation, or issues, or both? (if we are using the boards, should others have permissions to edit them?)
