### ISSUE TITLE
Version 2 of Name Badge Sticker Sheet

### ISSUE THREAD

**Issue by jdorfman** [sustainers/events#16]
Version 1 came out pretty good:

![image](https://user-images.githubusercontent.com/398230/45371615-dbfcb780-b59f-11e8-838a-f759246f85a7.png)

**Things to fix:**

@jdorfman
- [x] Talk to SM about kiss cut fail - https://cl.ly/5d02813d770a

@elioqoshi
- [x] Resize badge to 4"x3" (adjust photo permission stickers accordingly)
- [x] Add "Name Badge" caption under badge
- [x] Add Made with <3 by Sticker Mule - https://cl.ly/3y1E2M061Z0T | https://cl.ly/556134f9bb20
- [x] Convert circles to "webcam spy blockers" - https://cl.ly/139b8ad971d9 | https://cl.ly/564db68a7de0

**Comment by elioqoshi** [comment]
@jdorfman can you link the file I sent you here so it can be in the open?

Might need some assistance from @anxh3l0 here as well

**Comment by jdorfman** [comment]
@elioqoshi sure thing: https://cl.ly/aa18a737f14d

**Comment by AnXh3L0** [comment]
@jdorfman I made a draft with the changes you requested as seen in the image attached below:
Feedback appreciated! :)

![sticker sheet](https://user-images.githubusercontent.com/25004151/45458684-01e7a080-b6f5-11e8-9b6f-286171df3653.png)

**Comment by jdorfman** [comment]
@AnXh3L0 looking great. Can you add the following?

![image](https://user-images.githubusercontent.com/398230/45463759-65a4a600-b6c2-11e8-904e-48f1b7083c65.png)

"Mountain Icon" for Webcam Blocker:
![image 2018-09-12 at 7 31 29 pm](https://user-images.githubusercontent.com/398230/45463787-7fde8400-b6c2-11e8-8ba3-1624a2693c52.png)

**And adjust:**

![image](https://user-images.githubusercontent.com/398230/45464107-ea43f400-b6c3-11e8-9045-4dd2b777d4a0.png)

That will print 4"x3"?

**Comment by AnXh3L0** [comment]
@jdorfman Added the other webcam blocker icons and fixed the spacing on both sides.
Yes, the name badge part is 4"x3".

![sticker sheet](https://user-images.githubusercontent.com/25004151/45475447-b822a880-b73c-11e8-8cc6-ae5a1da2486d.png)

**Comment by jdorfman** [comment]
@AnXh3L0 perfecto. Can you `create outlines` and attach the AI?

thanks!

**Comment by AnXh3L0** [comment]
@jdorfman Attached you'll find a zip that contains the SVG, PDF and PNG file formats.

Cheers!

[Sustain-Summit-2018-Sticker-Sheet.zip](https://github.com/sustainers/events/files/2379451/Sustain-Summit-2018-Sticker-Sheet.zip)
