### ISSUE TITLE
Fix OC ticket receipt email

### ISSUE THREAD

**Issue by jdorfman** [sustainers/events#18]
Showing last years info

![cloudapp annotation 2018-09-13 at 7 23 43 am png](https://user-images.githubusercontent.com/398230/45494631-56574400-b726-11e8-8f88-023a362efc5d.png)

**Comment by piamancini** [comment]
good catch ! i'm on it

**Comment by jdorfman** [comment]
@piamancini good to close?

**Comment by jdorfman** [comment]
Actually reopen if needed
