### ISSUE TITLE
Create ticket purchase page on OC

### ISSUE THREAD

**Issue by jdorfman** [sustainers/events#2]
This will be linked from the "Tickets" page

![image](https://user-images.githubusercontent.com/398230/39721567-ce773e32-51f4-11e8-9bec-4d1161acb382.png)

**Comment by daiyi** [comment]
What is the website shown in the screenshot? (I can't seem to be able to google for it!)

**Comment by jdorfman** [comment]
@daiyi it's a mockup for the new site that is currently being developed. I am starting to put together all of the copy for each page and this is a blocker. =)

**Comment by jdorfman** [comment]
@daiyi I would love to collaborate with you on some design for the new site. I think it would be cool if some objects were hand drawn like venue map or something along those lines. DM me your gmail and I'll add you to the folders.

**Comment by jdorfman** [comment]
I just figured out I can create it https://opencollective.com/sustainoss/events/new#

I guess the hard part is figuring out which ticket type(s) to use.

**Comment by jdorfman** [comment]
Need to look into why the OG image is hidden when pasting a link in Slack to the OC ticket/sponsor page - https://cl.ly/3C1f1K3k1K1H
