### ISSUE TITLE
Notes - Sept 27

### ISSUE THREAD

**Issue by coderberry** [sustainers/events#21]
#### Attendees

* Justin
* Eric
* Cat
* Richard

#### Actionable Items

- [x] Justin send Cat contact details to meet up on 24th.
- [x] Justin will ping Pia about CloudFlare status

#### Notes

Justin - Travis foundation has something called diversity tickets. The date has come for us to end it. We are considering extending it for another week. Will discuss with Pia. 

Justin - I arrive Oct 23. Will meet up with Cat. Will email Cat with contact info.

Richard - Has scholarship from Protocol Labs come in yet?

Justin - Not yet, but it should.

**Comment by jdorfman** [comment]
This helped more than you know. Thanks @coderberry

**Comment by andrew** [comment]
Oops, sorry! 🙈

**Comment by jdorfman** [comment]
haha all good @andrew
