### ISSUE TITLE
Notes - Oct 4

### ISSUE THREAD

**Issue by coderberry** [sustainers/events#22]
# Sustain Summit Planning - Oct 4, 2018

#### Attendees

* Justin
* Eric
* Cat
* Pia
* Yanna w/ Kiwi Fund (kiwi.com)

#### Actionable Items

- [ ] Pia - Send email to 5 new people who joined
- [x] Pia - Send Justin the CSV with all the emails for mailchimp email blast
- [ ] Pia - set up Sevier with scholarship ticket
- [ ] Pia will follow up with tickets for Will Norris and Chris Stebona
- [ ] Cat will connect Pia with the reporter
- [ ] Close sales of tickets at 80 total (currently 72)

#### Notes

Pia - Did emails last week for all attendees. Will do new round for people who joined afterwards.  Did more work for travel agency. Followed up with MS about donation. Looking into why it hasn’t happened yet. Jeff Macathur is coming and asked about donation.

Eric - CodeFund showed 320.1k ad impressions and 486 clicks

Yanna - How we can support OSS teams. kiwi.com has fund to support open source teams to support travel to conferences, etc. Python related. They will pay for travel costs. Generate vouchers for flights. Fly to conference for free. https://kiwi.com

 Cat - Will Norris and Chris Stebona want to come but have had issues signing up. Pia confirmed that they are already signed up. Not appearing on website yet. Google corporate communications is excited about the conference. Wanted to know if reporter can interview Pia about open collective. Pia - sounds good.

Pia - Ben has been immensely helpful in dealing with travel agency. Big thanks to Ben. He paid for a lot of tickets himself out of pocket.

We currently have 72 sold tickets so far. We will close at 80 tickets.

**Comment by jdorfman** [comment]
@alnermcgunn's email sent

![image](https://user-images.githubusercontent.com/398230/46679389-bdd4a800-cb9b-11e8-9cf5-52eb4e692fed.png)
