### ISSUE TITLE
Find sponsors/partners

### ISSUE THREAD

**Issue by jdorfman** [sustainers/events#4]
✅ = Good to go
⏱ = Waiting to hear back

----
- [x] Tidelift ✅
- [ ] Dollar Shave Club ⏱ 
- [ ] GitHub ⏱
- [ ] Mozilla ⏱
- [ ] PSF
- [ ] Linux Foundation
  - [ ] CHAOSS
  - [ ] JS Foundation
  - [ ] CNCF
  - [ ] Core Infrastructure Initiative
- [ ] StackPath
- [ ] 8th Light
- [ ] Waffle.io
- [ ] RedHat
- [ ] Iron.io
- [ ] CodePilot.io
- [ ] Alfred P. Sloan Foundation
- [ ] Lawrence Livermore National Laboratory

## Media
- [ ] [Gitcoin](https://gitcoin.co/) ⏱
- [ ] Changelog
- [ ] nixCraft
- [ ] [The New Stack](https://thenewstack.io)
- [ ] [CodeFund](https://codesponsor.io/)
- [ ] OpenSouce.com

https://sustainoss.org/sponsors/

**Comment by coderberry** [comment]
CodeFund will provide ads to promote the event. Please let me know when you are ready for this to happen.

**Comment by jdorfman** [comment]
Soon

**Comment by jdorfman** [comment]
This is now a spreadsheet. Ask for permission.
