### ISSUE TITLE
How are we framing Sustain UK

### ISSUE THREAD

**Issue by piamancini** [sustainers/events#5]
wins
- community / diverse group of people 
- report 
- collaborations?  
improve
- collaboration. 
- raw material for others to write about the subject
- a little bit more following up / community engagement after the event?

Nexts steps
- send an email asking about collaborations. did you apply the discussions from the day? (@piamancini + @jdorfman 
- @jdorfman's list for sponsorships 
- Have the leftover budget numbers (@alnermcgunn)
- circulate the raw material on what's sustaining open source to help us shape the narrative building on what we previously discussed. (@piamancini)

For next call: 
- review attendees from last time and see which we need to reach out to. @BenJam + @jdorfman 
- work on the narrative. Improve the language in the website about what we mean with sustainer? Bring into the website the conversation we had last time. We need to acknowledge the contradictions in sustaining open source. Specially the fact the a 'surveillance capitalist organization' is hosting the event. 

Travel Scholarships (@BenJam)

**Comment by coderberry** [comment]
My notes from meeting:

Google @ London

Contributions coming in already

* Figure out how we want to invite
* Open ticket sales
* Spend time framing why we are doing this
* What did we learn, how do we go from here

Report was super useful but under utilized.

What collaborations came out of the last conference? We don’t think there was any done. There were 16 project launched but none came out of that.

Need to send an email to prior participants and ask how they applied what they discussed that day?

This time, raw data needs to be more accessible. This enables others to write blog posts. Give people raw materials for others to write about.

Make this the starting point of something bigger than the 1 day conference. More hand-holding of agreements. Someone needs to be bottom-lining community engagement after the event.

What lacked last time in terms of representation?
* Gender
* Minorities
* Non-US citizens
* Different OSS big groups
* Lacked coders (sole proprietors)

Funds are primarily for operational costs and bringing people from out of country. It’s only a 100 person event so there is not a need for advertising.
