### ISSUE TITLE
notes from meeting 6/21

### ISSUE THREAD

**Issue by piamancini** [sustainers/events#6]
language framework for sustainability, the scaffolding on top of which we can build stuff. 
core words: resilience / thriving 
financial, community, individual sustainability
how it weaves together. 

during sustainOSS SF people didn't understand which facet of sustainability 

Next steps: 

- Put together a vision doc (@jdorfman)

- build a smaller circle from attendee list. 
all of us: go through the attendee list and think who can be part of this first circle and then socialize more broadly
Josh/Cat 
Robert Rickter 
Eirenn Leverett
Kelsey (Tessel)

- Share this with a smaller circle

**Comment by jdorfman** [comment]
**Vision & Goal doc:** https://docs.google.com/document/d/1YJ-3-Q99oO9b-CUUqqUEyWLlmcWsRQe6WbDD3x7-25w/edit#

**My notes:**

keywords: resilience, survival, thriving, survive, growing

@alnermcgunn  
* language framework, not the final answer, over read into it, tag these as financial sessions, community, etc
* richer analysis
* burnout, negative, healthy community
* minimum viable verbiage
* a lot of people pivoted towards business last year
* diversity came up constantly last year
* 5-7 people committee before rolling out ideas to public
  * [Saron Yitbarek](https://twitter.com/saronyitbarek)
* look at last years attendees for advisory board
* 1 page vision and goal doc - start
* asked josh to review budget, $11k
* feeling posistive about doing in uk, new batch of people 

@piamancini 
* working on budget

@BenJam 
* numfocus wrote piece resiliance
* consumer reports
* liability, motivate orgs about sustainability
* “diversity of skills”

**Comment by jdorfman** [comment]
I had a great call with @elioqoshi around branding. He is going to put a proposal together for Monday (06-25-2018).

**Comment by elioqoshi** [comment]
Sent the proposal :)

Excited!
